### ISSUE TITLE
fast-async not working when awaiting non-promise

### ISSUE THREAD

**Issue by runn1ng** [MatAtBread/fast-async#9]
Consider this small code. It *is* working with Babel implementation.

````javascript
async function returnsFive() {
  var three = 3;
  var threeP = await three;
  return threeP+2;
}

returnsFive().then(k=>console.log(k), e=>console.error("err", e))
````
See [babel repl](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Ces2015-loose%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&experimental=true&loose=false&spec=false&code=async%20function%20returnsfive()%20%7B%0A%20%20var%20three%20%3D%203%3B%0A%20%20var%20threeP%20%3D%20await%20three%3B%0A%20%20return%20threeP%2B2%3B%0A%7D%0A%0Areturnsfive().then(k%3D%3Econsole.log(k)%2C%20e%3D%3Econsole.error(%22err%22%2C%20e))).

With fast-async, I get

`index.js:1362 err TypeError: three.then is not a function`

That's not good.

I cannot right now find a formal specification for async/await, so I am not sure which implementation is "correct".

**Comment by runn1ng** [comment]
Oh, it's a nodent issue that is actually a feature, I think. OK. Closing

https://www.npmjs.com/package/nodent#gotchas-and-es7-compatibility

**Comment by matAtWork** [comment]
Yes, this seems to be an edge case not covered by the spec. Most references within the spec say "await must be followed by an expression evaluating to a Promise", but the standard generator implementation always wraps the yielded value in a Promise (inside the 'spawn' routine), which means you don't have to 'await' a Promise, since whatever you put after it will get wrapped.

Nodent has an option `wrapAwait` to always wrap the value, but it does slow things down quite a bit.

If you find a definitive answer, please let me have the reference.

**Comment by runn1ng** [comment]
http://stackoverflow.com/questions/38884570/what-should-happen-with-await-when-the-expression-after-the-keyword-does-not-e/38884761#38884761

**Comment by matAtWork** [comment]
Interestingly, I can't find the definition of NewPromiseCapability as used in the spec - it would make sense to assume it requires wrapping, however it's still not clear to me, so I'll leave it as an option for now.

Out of interest, what is your use-case, in the sense of when is awaiting a non-Promise useful to you?

**Comment by matAtWork** [comment]
..I take that back, it's at http://www.ecma-international.org/ecma-262/6.0/index.html#sec-newpromisecapability. So it looks like wrapping is the standard, and the nodent optimization (not wrapping everything in a Promise) is possible optimization. I'll work out how to handle this case and see if there's a non-breaking solution
